// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PocSbCredito.Infrastructure.Database;

#nullable disable

namespace PocSbCredito.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251108192931_CreatingEntities")]
    partial class CreatingEntities
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.10");

            modelBuilder.Entity("PocSbCredito.Infrastructure.Database.Entities.TB_Empresa", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("Cnpj")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("cnpj");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("email");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("nome");

                    b.Property<string>("StRegistro")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("TEXT")
                        .HasColumnName("st_registro");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.Property<decimal?>("ValorLimiteCredito")
                        .HasColumnType("TEXT")
                        .HasColumnName("valor_limite_credito");

                    b.HasKey("Id");

                    b.ToTable("tb_empresa");
                });

            modelBuilder.Entity("PocSbCredito.Infrastructure.Database.Entities.TB_FundoFIDC", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("Cnpj")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("cnpj");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("nome");

                    b.Property<decimal>("RentabilidadeMensal")
                        .HasColumnType("TEXT")
                        .HasColumnName("rentabilidade_mensal");

                    b.Property<decimal>("SaldoDisponivel")
                        .HasColumnType("TEXT")
                        .HasColumnName("saldo_disponivel");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.ToTable("tb_fundofidc");
                });

            modelBuilder.Entity("PocSbCredito.Infrastructure.Database.Entities.TB_Investidor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("email");

                    b.Property<Guid>("FundoId")
                        .HasColumnType("TEXT")
                        .HasColumnName("fundo_id");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("nome");

                    b.Property<decimal>("SaldoAplicado")
                        .HasColumnType("TEXT")
                        .HasColumnName("saldo_aplicado");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("FundoId");

                    b.ToTable("tb_investidor");
                });

            modelBuilder.Entity("PocSbCredito.Infrastructure.Database.Entities.TB_OperacaoAntecipacao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("DataOperacao")
                        .HasColumnType("TEXT")
                        .HasColumnName("data_operacao");

                    b.Property<int>("DiasMedios")
                        .HasColumnType("INTEGER")
                        .HasColumnName("dias_medios");

                    b.Property<Guid>("EmpresaId")
                        .HasColumnType("TEXT")
                        .HasColumnName("empresa_id");

                    b.Property<Guid>("FundoId")
                        .HasColumnType("TEXT");

                    b.Property<string>("StatusOperacao")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("TEXT")
                        .HasColumnName("status_operacao");

                    b.Property<decimal>("TaxaMensal")
                        .HasColumnType("TEXT")
                        .HasColumnName("taxa_mensal");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.Property<decimal>("ValorTotalAntecipado")
                        .HasColumnType("TEXT")
                        .HasColumnName("valor_total_antecipado");

                    b.Property<decimal>("ValorTotalOriginal")
                        .HasColumnType("TEXT")
                        .HasColumnName("valor_total_original");

                    b.HasKey("Id");

                    b.HasIndex("EmpresaId");

                    b.HasIndex("FundoId");

                    b.ToTable("tb_operacaoantecipacao");
                });

            modelBuilder.Entity("PocSbCredito.Infrastructure.Database.Entities.TB_Recebivel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("DataEmissao")
                        .HasColumnType("TEXT")
                        .HasColumnName("data_emissao");

                    b.Property<DateTime>("DataVencimento")
                        .HasColumnType("TEXT")
                        .HasColumnName("data_vencimento");

                    b.Property<Guid>("EmpresaId")
                        .HasColumnType("TEXT")
                        .HasColumnName("empresa_id");

                    b.Property<string>("NumeroDocumento")
                        .HasColumnType("TEXT")
                        .HasColumnName("numero_documento");

                    b.Property<Guid>("OperacaoAntecipacaoId")
                        .HasColumnType("TEXT")
                        .HasColumnName("operacao_antecipacao_id");

                    b.Property<string>("Pagador")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("pagador");

                    b.Property<string>("StatusRecebivel")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("TEXT")
                        .HasColumnName("status_recebivel");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.Property<decimal?>("ValorAntecipado")
                        .HasColumnType("TEXT")
                        .HasColumnName("valor_antecipado");

                    b.Property<decimal>("ValorOriginal")
                        .HasColumnType("TEXT")
                        .HasColumnName("valor_original");

                    b.HasKey("Id");

                    b.HasIndex("EmpresaId");

                    b.HasIndex("OperacaoAntecipacaoId");

                    b.ToTable("tb_recebivel");
                });

            modelBuilder.Entity("PocSbCredito.Infrastructure.Database.Entities.TB_Investidor", b =>
                {
                    b.HasOne("PocSbCredito.Infrastructure.Database.Entities.TB_FundoFIDC", "FundoFK")
                        .WithMany()
                        .HasForeignKey("FundoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FundoFK");
                });

            modelBuilder.Entity("PocSbCredito.Infrastructure.Database.Entities.TB_OperacaoAntecipacao", b =>
                {
                    b.HasOne("PocSbCredito.Infrastructure.Database.Entities.TB_Empresa", "EmpresaFK")
                        .WithMany()
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PocSbCredito.Infrastructure.Database.Entities.TB_FundoFIDC", "FundoFK")
                        .WithMany()
                        .HasForeignKey("FundoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EmpresaFK");

                    b.Navigation("FundoFK");
                });

            modelBuilder.Entity("PocSbCredito.Infrastructure.Database.Entities.TB_Recebivel", b =>
                {
                    b.HasOne("PocSbCredito.Infrastructure.Database.Entities.TB_Empresa", "EmpresaFK")
                        .WithMany()
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PocSbCredito.Infrastructure.Database.Entities.TB_OperacaoAntecipacao", "OperacaoAntecipacaoFK")
                        .WithMany()
                        .HasForeignKey("OperacaoAntecipacaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EmpresaFK");

                    b.Navigation("OperacaoAntecipacaoFK");
                });
#pragma warning restore 612, 618
        }
    }
}
